monitor.bluez.rules = [
  {
    matches = [
      {
        device.api = "bluez5"
        device.address = "78:2B:64:DE:4D:9C"
      }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink ]
      }
    }
  }
]
