# brews
brew "bash-completion@2"
brew "btop"
brew "dockutil"
brew "eza"
brew "fastfetch"
brew "git"
brwe "git-delta"
brew "node"
brew "starship"

# casks
cask "alacritty"
cask "bitwarden"
cask "librewolf", args: { "no-quarantine" => true }
cask "mullvad-browser"
cask "protonvpn"
cask "rectangle"
cask "vscodium"
cask "zed"

# fonts
cask "font-fira-code-nerd-font"
